name: Set reviewer for v18
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "18.0"
  push:
    branches:
      - "18.0"

jobs:
  pr18:
    runs-on: ubuntu-latest

    #env:
    #  GH_TOKEN: ${{ github.token }}
    #  GH_TOKENS: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.PR18_APP_ID }}
        private-key: ${{ secrets.PR18_SECRET_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Assign reviewer
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        url: ${{ github.event.pull_request.html_url }}
      run: |
        gh pr edit "$url" --add-reviewer rycks
        gh pr edit "$url" --add-reviewer lvessiller-opendsi

